import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "@/components/footer"
import AuthProvider from "./providers/auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "FSW Barber",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="dark">
            <body className={inter.className}>
                <AuthProvider>
                    <main className="flex min-h-svh flex-col">
                        <div className="flex-1 pb-6">{children}</div>
                        <Footer />
                    </main>
                </AuthProvider>
                <Toaster />
            </body>
        </html>
    )
}
